CU-8678g1zgg - wc-sdk: encrypt, decrypt and decryptFromArray methods
CityOfZion/wallet-connect-sdk pull request #81
Opened 2023-08-31 13:42 UTC by endkeyCoder

2023-08-31 13:42 UTC, melanke commented
Task linked: [CU-8678g1zgg wc-sdk: encrypt, decrypt and decryptFromArray methods](https://app.clickup.com/t/8678g1zgg)

2023-09-01 12:28 UTC, melanke requested changes
Ficou correto, só alguns detalhes

2023-09-01 12:28 UTC, melanke commented on common/changes/@cityofzion/wallet-connect-sdk-core/CU-8678g1zgg_2023-08-31-13-48.json
> +      "comment": "The methods encrypt, decrypt and decryptFromArray methods was implemented",
Corrigindo o inglês seria:
```suggestion
      "comment": "The encrypt, decrypt and decryptFromArray methods have been implemented",
```

Mas gostaria de acrescentar esse "New encryption methods" na frente
```suggestion
      "comment": "New encryption methods: The encrypt, decrypt, and encrypt From Array methods have been implemented",
```

2023-09-01 12:28 UTC, melanke commented on common/changes/@cityofzion/wallet-connect-sdk-react/CU-8678g1zgg_2023-08-31-13-48.json
> +      "comment": "The methods encrypt, decrypt and decryptFromArray methods was implemented",
mesma coisa aqui:
```suggestion
      "comment": "New encryption methods: The encrypt, decrypt, and encrypt From Array methods have been implemented",
```

2023-09-01 12:28 UTC, melanke commented on common/changes/@cityofzion/wallet-connect-sdk-wallet-core/CU-8678g1zgg_2023-08-31-13-48.json
> +      "comment": "The methods encrypt, decrypt and decryptFromArray methods was implemented",
Mesma coisa:
```suggestion
      "comment": "New encryption methods: The encrypt, decrypt, and encrypt From Array methods have been implemented",
```

2023-09-01 12:28 UTC, melanke commented on packages/wallet-connect-sdk-core/src/index.ts
> +    async decrypt(payload: EncryptedPayload): Promise<string> {
Pula uma linha entre um método e outro. (vou criar uma issue pra eslint pra facilitar isso)
```suggestion

    async decrypt(payload: EncryptedPayload): Promise<string> {

```

2023-09-01 12:28 UTC, melanke commented on packages/wallet-connect-sdk-core/src/index.ts
> +    async decryptFromArray(payloads: EncryptedPayload[]): Promise<{
Pula linha aqui tb pf
```suggestion

    async decryptFromArray(payloads: EncryptedPayload[]): Promise<{

```

2023-09-01 12:28 UTC, melanke commented on packages/wallet-connect-sdk-core/src/index.ts
> +        return resp as {
Pode usar o tipo q vc mesmo criou ^^
https://github.com/CityOfZion/neon-dappkit/pull/6/files#diff-92dc83b06ff8acd52e43dc13a5953c9d0e47832c954983979468bb0309b33a2aR43

2023-09-01 12:28 UTC, melanke commented on packages/wallet-connect-sdk-core/src/index.ts
> +    }> {
Aqui tb pode usar o tipo

2023-09-01 12:28 UTC, melanke commented on packages/wallet-connect-sdk-react/package.json
> +    "@cityofzion/neon-dappkit-types": "~0.0.1"
0.0.5 sem o ~ e nem o ^

2023-09-01 12:28 UTC, melanke commented on packages/wallet-connect-sdk-wallet-core/src/adapter.ts
> +  }> {
o tipo aqui tb

2023-09-01 13:06 UTC, endkeyCoder commented on common/changes/@cityofzion/wallet-connect-sdk-wallet-core/CU-8678g1zgg_2023-08-31-13-48.json
> +      "comment": "The methods encrypt, decrypt and decryptFromArray methods was implemented",
Adicionei a frase que vc pediu

2023-09-01 13:07 UTC, endkeyCoder commented on packages/wallet-connect-sdk-core/src/index.ts
> +    async decrypt(payload: EncryptedPayload): Promise<string> {
Coloquei o espaçamento entre os métodos

2023-09-01 13:07 UTC, endkeyCoder commented on packages/wallet-connect-sdk-core/src/index.ts
> +    async decryptFromArray(payloads: EncryptedPayload[]): Promise<{
coloquei o espaçamento entre os métodos

2023-09-01 13:08 UTC, endkeyCoder commented on packages/wallet-connect-sdk-core/src/index.ts
> +        return resp as {
passei a importar e usar o DecryptFromArrayResult

2023-09-01 13:08 UTC, endkeyCoder commented on packages/wallet-connect-sdk-core/src/index.ts
> +    }> {
passei a importar e usar o DecryptFromArrayResult

2023-09-01 13:08 UTC, endkeyCoder commented on packages/wallet-connect-sdk-react/package.json
> +    "@cityofzion/neon-dappkit-types": "~0.0.1"
mudei a versão

2023-09-01 13:08 UTC, endkeyCoder commented on packages/wallet-connect-sdk-wallet-core/src/adapter.ts
> +  }> {
passei a importar e usar o DecryptFromArrayResult

2023-09-01 13:34 UTC, merged